# Generated by Django 4.0 on 2022-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=250, unique=True)),
                ('video_title', models.CharField(max_length=250)),
                ('video_thumbnail', models.URLField()),
                ('channel_id', models.CharField(max_length=250)),
                ('channel_title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1250)),
                ('uploaded_at', models.DateTimeField()),
            ],
        ),
    ]
